In [1]:
#assignment 1
#data slection pre-processing and model building

In [2]:
#importin the libraries 
import numpy as np
import pandas as pd

In [3]:
#loading the excel file

file=pd.read_excel(r"C:\Users\hp\OneDrive\Desktop\churns.xlsx" )
df=pd.DataFrame(file)

print(df.head(5))
print(df.columns)
df.shape

   CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0  
Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')


(10000, 11)

In [4]:
#handling the missing values
print(df.isnull().sum())

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64


In [5]:
df[np.isinf(df.select_dtypes(include=[np.number]))].count()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
#handling duplicate values
print(df.duplicated().any())

False


In [7]:
df.rename(columns={"is_churn":"Exited"},inplace=True)

In [8]:
#identifing and separating the target variable
y = df["Exited"]
X = df.drop("Exited", axis=1)

In [9]:
#one hot encoding
X=pd.get_dummies(X,drop_first=True,dtype=int)

In [10]:
#spliting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [11]:
df.shape

(10000, 11)

In [12]:
#standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
#file of standard vale
pd.DataFrame(X_train).to_excel(r"C:\Users\hp\OneDrive\Desktop\scaled_train.xlsx", index=False)

In [14]:
#model training
#logistic regression
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression()
log_model.fit(X_train,y_train)
log_predict=log_model.predict(X_test)
print(log_predict)

[0 0 0 ... 0 0 0]


In [15]:
#evalution of logistic regression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print("Accuracy score :- ",accuracy_score(y_test,log_predict))
print("Precision score :- ",precision_score(y_test,log_predict))
print("Recall score :- ",recall_score(y_test,log_predict))
print("F1 score :- ",f1_score(y_test,log_predict))

Accuracy score :-  0.811
Precision score :-  0.5524475524475524
Recall score :-  0.2010178117048346
F1 score :-  0.2947761194029851


In [16]:
#knn classification
from sklearn.neighbors import KNeighborsClassifier
knn_model= KNeighborsClassifier(n_neighbors =3)
knn_model.fit(X_train,y_train)
knn_predict=knn_model.predict(X_test)
print(knn_predict)

[0 0 0 ... 1 0 1]


In [17]:
#evalution of Knn classification 
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print("Accuracy score :- ",accuracy_score(y_test,knn_predict))
print("Precision score :- ",precision_score(y_test,knn_predict))
print("Recall score :- ",recall_score(y_test,knn_predict))
print("F1 score :- ",f1_score(y_test,knn_predict))

Accuracy score :-  0.832
Precision score :-  0.6021505376344086
Recall score :-  0.42748091603053434
F1 score :-  0.5


In [18]:
#decision tree
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier()
dt_model.fit(X_train,y_train)
dt_predict=dt_model.predict(X_test)
print(dt_predict)

[1 0 0 ... 0 0 1]


In [19]:
#evalution of Decision tree
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print("Accuracy score :- ",accuracy_score(y_test,dt_predict))
print("Precision score :- ",precision_score(y_test,dt_predict))
print("Recall score :- ",recall_score(y_test,dt_predict))
print("F1 score :- ",f1_score(y_test,dt_predict))

Accuracy score :-  0.7755
Precision score :-  0.43665158371040724
Recall score :-  0.4910941475826972
F1 score :-  0.4622754491017964


In [20]:
#confusion metrics for all three algo
from sklearn.metrics import confusion_matrix
print("Confusion metrics of Logistic Regression :- \n",confusion_matrix(y_test,log_predict))
print("Confusion metrics of Knn classification   :- \n",confusion_matrix(y_test,knn_predict))
print("Confusion metrics of Decision Tree :- \n",confusion_matrix(y_test,dt_predict))

Confusion metrics of Logistic Regression :- 
 [[1543   64]
 [ 314   79]]
Confusion metrics of Knn classification   :- 
 [[1496  111]
 [ 225  168]]
Confusion metrics of Decision Tree :- 
 [[1358  249]
 [ 200  193]]


In [21]:
#Best model
best_model=knn_model

In [22]:
#final prediction
print("Final Model Used: KNN")
final_prediction=best_model.predict(X_test)
print(final_prediction)

Final Model Used: KNN
[0 0 0 ... 1 0 1]


In [23]:
#classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, final_prediction))


              precision    recall  f1-score   support

           0       0.87      0.93      0.90      1607
           1       0.60      0.43      0.50       393

    accuracy                           0.83      2000
   macro avg       0.74      0.68      0.70      2000
weighted avg       0.82      0.83      0.82      2000



In [24]:
#Saving the file
X.to_excel(r"C:\Users\hp\OneDrive\Desktop\assignment1.xlsx",index=False)